name: "Changelog Validator"

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  validate-changelog:
    name: Changelog validator
    runs-on: ubuntu-latest
    steps:
    - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

    - name: Checkout Branch
      uses: actions/checkout@v4.2.2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x

    - name: Validate Changelog
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
      run: |
        cd "Tools/_NF/changelog"
        node validate_changelog.js
      shell: bash
